# Generated by Django 5.0.6 on 2024-07-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosadicionales',
            name='rut',
            field=models.CharField(default='00000000000', max_length=20, unique=True, verbose_name='RUT'),
        ),
    ]
